use_frameworks!

target 'iOSGradientView_Example' do
  pod 'iOSGradientView', :path => '../'

  target 'iOSGradientView_Tests' do
    inherit! :search_paths
    pod 'iOSGradientView', :path => '../'
    
  end
end
